apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: flex-vedtak-mock
  namespace: flex
  labels:
    team: flex
spec:
  image: {{ image }}
  port: 8080
  ingresses:
    - "https://flex-vedtak-mock.dev.nav.no"
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 256Mi
  liveness:
    path: internal/isAlive
  readiness:
    path: internal/isReady
  env:
    - name: SYKMELDINGER_BACKEND_PROXY_ROOT
      value: "https://sykmeldinger-backend-proxy.dev.nav.no"
    - name: SPINNSYN_ROOT
      value: "https://spinnsyn-backend-proxy.dev.nav.no"
    - name: FLEXINNTEKTSMELDING_ROOT
      value: "https://flex-inntektsmelding-proxy.dev.nav.no"
    - name: ENVIRONMENT
      value: "q1"
    - name: SYFOAPI_ROOT
      value: "https://syfoapi.dev.nav.no"
    - name: OPPRETT_VEDTAK_ROOT
      value: "https://spinnsyn-backend-mock-proxy.dev.nav.no/api/v1/mock/vedtak"
